const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   STORE_QUEUED_CARDS: "STORE_QUEUED_CARDS",
   INCREMEMNT_QUEUE_INDEX: "INCREMEMNT_QUEUE_INDEX:",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
   RESET_QUEUE: "RESET_QUEUE",
   STORE_EDITABLE_CARD: "STORE_EDITABLE_CARD",
};

export default actions;
